# Generated by Django 4.2.13 on 2024-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_galleryimage_headlineimage_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='gallery/videos/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
