# Generated by Django 4.2.13 on 2024-06-23 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_galleryvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='headlineimage',
            name='image',
            field=models.ImageField(upload_to='headline', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
